name: hexla
version: '0.2.0.0'
author: Chris Stryczynski
maintainer: Chris Stryczynski
license: BSD3
extra-source-files:
- ChangeLog.md
dependencies:
- base
- directory
- unix
- containers
- rainbox
- rainbow
- byteunits >=0.3.0.2 && <1.0
- filepath
- time
- text
- optparse-applicative
- typed-process
- split
- string-conversions
executables:
  hexla:
    main: Main.hs
